name: Publish to npm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Fixed typo: 'package' -> 'packages'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated from v2 to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated from v3 to v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'  # Added registry URL

      - name: Install dependencies
        run: npm ci  # Changed from 'npm install' to 'npm ci' for more reliable installs

      - name: Build the project
        run: npm run build

      - name: Configure npm registry
        run: |
          echo "@ranaHP:https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

      - name: Publish to npm
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}