name: Publish to npm

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated from v2 to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated from v3 to v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'  # Added registry URL
          scope: '@ranahp'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish to npm
        run: npm publish
        working-directory: ./build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}